# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2026 Linaro Limited

_anchors:
  baseline-job-pull-labs: &baseline-job-pull-labs
    template: baseline.jinja2
    kind: job
    priority: medium
    kcidb_test_suite: boot
    params:
      ramdisk: 'http://storage.kernelci.org/images/rootfs/buildroot/buildroot-baseline/20230703.0/{brarch}/rootfs.cpio.gz'

  ltp-params-pull-labs: &ltp-params-pull-labs
    boot_commands: nfs
    nfsroot: 'https://storage.kernelci.org/images/rootfs/debian/trixie-ltp/20251201.0/{debarch}'
    skip_install: "true"
    skipfile: skipfile-lkft.yaml
    workers: max

jobs:
  baseline-arm-pull-labs-demo: *baseline-job-pull-labs
  baseline-arm64-pull-labs-demo: *baseline-job-pull-labs
  baseline-x86-pull-labs-demo: *baseline-job-pull-labs

  ltp-smoke-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "smoketest"
    kcidb_test_suite: ltp

  ltp-syscalls-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "syscalls"
    kcidb_test_suite: ltp

  ltp-fs-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "fs"
    kcidb_test_suite: ltp

  ltp-mm-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "mm"
    kcidb_test_suite: ltp

  ltp-io-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "io"
    kcidb_test_suite: ltp

  ltp-ipc-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "ipc"
    kcidb_test_suite: ltp

  ltp-sched-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "sched"
    kcidb_test_suite: ltp

  ltp-cve-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "cve"
    kcidb_test_suite: ltp

  ltp-net-tcp-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "net.tcp_cmds"
    kcidb_test_suite: ltp

  ltp-cap-bounds-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "cap_bounds"
    kcidb_test_suite: ltp

  ltp-containers-pull-labs:
    template: ltp-pull-labs.jinja2
    kind: job
    params:
      <<: *ltp-params-pull-labs
      tst_cmdfiles: "containers"
    kcidb_test_suite: ltp
